apiVersion: v1
kind: Service
metadata:
  name: event-bus
  namespace: electronic-lock-app
spec:
  selector:
    app: event-bus
  ports:
  - port: 3004
    targetPort: 3004
    protocol: TCP
  type: ClusterIP
