apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: electronic-lock-app-ingress
  namespace: electronic-lock-app
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: electronic-lock-app.local
    http:
      paths:
      - path: /api/users(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: user-service
            port:
              number: 3001
      - path: /api/logs(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: log-service
            port:
              number: 3002
      - path: /api/locks(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: lock-service
            port:
              number: 3003
      - path: /api/events(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: event-bus
            port:
              number: 10000

      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port:
              number: 80
  - host: mobile.electronic-lock-app.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: mobile-frontend
            port:
              number: 80