apiVersion: v1
kind: Service
metadata:
  name: lock-service
  namespace: electronic-lock-app
spec:
  selector:
    app: lock-service
  ports:
  - port: 3003
    targetPort: 3003
    protocol: TCP
  type: ClusterIP
