apiVersion: v1
kind: Service
metadata:
  name: log-service
  namespace: electronic-lock-app
spec:
  selector:
    app: log-service
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
  type: ClusterIP
