apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-service
  template:
    metadata:
      labels:
        app: log-service
    spec:
      containers:
        - name: log-service
          image: log-service:latest
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: log-service
spec:
  selector:
    app: log-service
  ports:
    - port: 3002
      targetPort: 3002
