apiVersion: v1
kind: Service
metadata:
  name: mobile-frontend
  namespace: electronic-lock-app
spec:
  type: NodePort
  selector:
    app: mobile-frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081


