apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: electronic-lock-app
type: Opaque
data:
  POSTGRES_DB: ZWxlY3Ryb25pY19sb2NrX2FwcA==  # electronic_lock_app 
  POSTGRES_USER: cG9zdGdyZXM=  # admin
  POSTGRES_PASSWORD: cGFzc3dvcmQxMjM=  # admin
  