apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-bus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-bus
  template:
    metadata:
      labels:
        app: shared-bus
    spec:
      containers:
        - name: shared-bus
          image: shared-bus:latest
          ports:
            - containerPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: shared-bus
spec:
  selector:
    app: shared-bus
  ports:
    - port: 3004
      targetPort: 3004
